# This Makefile was generated by the Cake3
# https://github.com/grwlf/cake3

GUARD = .cake3/GUARD_$(1)_$(shell echo $($(1)) | md5sum | cut -d ' ' -f 1)

ifdef MAIN

# Main section

URCC = $(shell $(shell urweb -print-ccompiler) -print-prog-name=gcc)
URINCL = $(shell urweb -print-cinclude)
URVERSION = $(shell urweb -version)
.PHONY: all
all: ./Script.urp ./Test1.exe ./Test2.exe
.PHONY: clean
clean: 
	rm -rf .cake3 ./Script.o ./Test1.exe
.PHONY: run
run: ./Test1.exe
	./Test1.exe
./Test2.exe: ./Test2.urp $(call GUARD,URVERSION)
	urweb -dbms sqlite ./Test2
./Test1.exe: ./Test1.urp $(call GUARD,URVERSION)
	urweb -dbms sqlite ./Test1
./Script.o: ./Script.c $(call GUARD,URCC) $(call GUARD,URINCL)
	$(URCC) -c -I $(URINCL) -o ./Script.o ./Script.c
./Script.urp: ./Script.h ./Script.o
	touch ./Script.urp
./Test1.urp: ./Script.urp ./Test1.ur
	touch ./Test1.urp
./Test2.urp: ./Script.urp ./Test2.ur
	touch ./Test2.urp
$(call GUARD,URCC):
	rm -f .cake3/GUARD_URCC_*
	touch $@
$(call GUARD,URINCL):
	rm -f .cake3/GUARD_URINCL_*
	touch $@
$(call GUARD,URVERSION):
	rm -f .cake3/GUARD_URVERSION_*
	touch $@

else

# Prebuild/postbuild section

.PHONY: all
all: .fix-multy1
.PHONY: clean
clean: .fix-multy1
.PHONY: run
run: .fix-multy1
.PHONY: ./Test2.exe
./Test2.exe: .fix-multy1
.PHONY: ./Test1.exe
./Test1.exe: .fix-multy1
.PHONY: ./Script.o
./Script.o: .fix-multy1
.PHONY: ./Script.urp
./Script.urp: .fix-multy1
.PHONY: ./Test1.urp
./Test1.urp: .fix-multy1
.PHONY: ./Test2.urp
./Test2.urp: .fix-multy1
.INTERMEDIATE: .fix-multy1
.fix-multy1: 
	-mkdir .cake3
	urweb -print-cinclude >/dev/null
	$(MAKE) -f ./Makefile MAIN=1 $(MAKECMDGOALS)

endif
